Vertical tabs
ciena-frost/ember-frost-tabs pull request #64
Opened 2017-09-04 19:44 UTC by quincyle

### This project uses [semver](semver.org), please check the scope of this pr:

- [ ] #none# - documentation fixes and/or test additions
- [x] #patch# - backwards-compatible bug fix
- [ ] #minor# - adding functionality in a backwards-compatible manner
- [ ] #major# - incompatible API change

# CHANGELOG
- Fix a css issue when rendering horizontal tabs inside vertical tabs.

2017-09-26 15:58 UTC, EWhite613 commented
Approved

2017-09-26 15:59 UTC, juwara0 requested changes

2017-09-26 15:59 UTC, juwara0 commented on .travis.yml
> -cache:
We want to leave this cache in. Please do not remove it.

2017-09-26 16:05 UTC, juwara0 commented on tests/integration/components/frost-tab-test.js
> +    this.timeout(5000)
This should be written as a `describe` with a `beforeEach()` where the `setProperties()` and `render()` are handled and the `expects()` are inside the `it()`. If needed you can then put the `return wait()` in the `beforeEach`.

2017-09-26 16:15 UTC, juwara0 commented on tests/integration/components/frost-tab-test.js
> +    this.timeout(5000)
```
describe('when something is done', function() {
  beforeEach(function () {
    this.setProperties({})
    this.render()
    return wait()
  })

  it('should have expected outcome', function () {
   expect()
  })
})
```

2017-09-26 16:32 UTC, juwara0 approved these changes

2017-09-27 16:19 UTC, EWhite613 commented
Approved

2017-09-27 16:20 UTC, merged