Enhance frost-detail-tab-actions to display actions labels in popover. #88
ciena-frost/ember-frost-tabs pull request #89
Opened 2018-05-14 17:04 UTC by goforsatish

# Overview
* Enhance frost-detail-tab-actions to display actions labels in popover
## Does this PR close an existing issue?
Yes

## Summary
Enhance frost-detail-tab-actions to display action label in popover.
Currently, actions labels are displayed below the each action icon that makes action bar look cluttered in case of many actions on action bar as the icon as well as labels take space on action bar for an action. Displaying only actions icons on the action bar will provide more real estate for other icons. The tooltip will display the corresponding actin label on mouseover on each action.

## Issue Number(s)
* Closes #88

## Screenshots or recordings
<img width="742" alt="action-label-popover" src="https://user-images.githubusercontent.com/33549703/40011796-832bec48-57c6-11e8-8adf-de621e98489a.png">

## Checklist
* [ ] I have added tests that prove my fix is effective or that my feature works
* [x] I have evaluated if the _README.md_ documentation needs to be updated
* [x] I have evaluated if the _/tests/dummy/_ app needs to be modified
* [ ] I have evaluated if DocBlock headers needed to be added or updated
* [x] I have verified that lint and tests pass locally with my changes
* [ ] If a fork of a dependent package had to be made to address the issue this PR closes:
  * [ ] I noted in the fork's _README.md_ the reason the fork was created
  * [ ] I have opened an upstream issue detailing what was deficient about the dependency
  * [ ] I have opened an upstream PR addressing this deficiency
  * [ ] I have opened an issue in this repository to track this PR and schedule the removal of the usage of the fork

# Semver

**This project uses [semver](http://semver.org), please check the scope of this PR:**

- [ ] #none#
- [x] #patch#
- [ ] #minor#
- [ ] #major#

Examples:
* **NONE**
  * _README.md_ changes
  * test additions
  * changes to files that are not used by a consuming application (_.travis.yml_, _.gitignore_, etc)
* **PATCH**
  * backwards-compatible bug fix
    * nothing about how to use the code has changed
    * nothing about the outcome of the code has changed (though it likely corrected it)
  * changes to demo app (_/tests/dummy/_)
* **MINOR**
  * adding functionality in a backwards-compatible manner
    * nothing about how used to use the code has changed but using it in a new way will do new things
    * nothing about the outcome of the code has changed without having to first use it in a new way
    * addition of new CSS selectors
    * addition of new `ember-hook` selectors
* **MAJOR**
  * incompatible API change
    * using the code how used to will cease working
    * using the code how used to will have a different outcome
    * any changes to CSS selector names
    * any removal of CSS selectors
    * any changes to `ember-hook` selectors
    * possibly changes to test helpers (depends on the changes made)
  * any changes to the **_dependencies_** entry in the _package.json_ file

# CHANGELOG
* Enhance frost-detail-tab-actions to display actions labels in popover

2018-05-14 18:27 UTC, ccampbel commented
Regarding @notmessenger's earlier question, yes this change to add the popover to the vertical action bar is the intended UX.  
As mentioned, since this is meant to be a very constrained space with small icons, there isn't much room for text.  Therefore, the idea is to use very simple, common icon metaphors for these actions as well as offering a popover with the full action label that appears on hover.
One thing I noticed from the pictures above in this PR, the precise visuals don't match the visual spec:
- the color of the popover is incorrect -- it should follow the hover tooltip spec (BG: Grey_2 @ 85% opacity)
- the popover should be shifted over slightly such that the triangle portion of it overlaps with the edge of the action strip itself.  Again, see the visual design in the link above.

![image](https://user-images.githubusercontent.com/17321596/40016007-fd9a7baa-5782-11e8-92ef-d3831c71a0fc.png)

2018-05-29 13:16 UTC, goforsatish commented
I have made the changes according to PR comments. Please review . 

![action-bar](https://user-images.githubusercontent.com/33549703/40661145-9f3663d6-6370-11e8-8ac1-f472c4e30b67.png)

2018-05-29 13:21 UTC, ccampbel commented
Thanks for making the updates.  Looks good.

2018-05-29 17:49 UTC, goforsatish commented
Action bar panel with action icon : 
<img width="699" alt="action-bar-1" src="https://user-images.githubusercontent.com/33549703/40675874-9c90508a-6396-11e8-8de9-738702b1f1d2.png">

On Action icon hover : 
<img width="717" alt="action-bar-2" src="https://user-images.githubusercontent.com/33549703/40675891-acd33ca0-6396-11e8-86f8-7f29b14a6169.png">

2018-05-30 14:30 UTC, notmessenger commented on tests/dummy/app/pods/demo/more-detail-tabs/controller.js
> +    @computed('selectedTab')
Why the extra space?

2018-05-30 14:30 UTC, notmessenger commented on tests/dummy/app/pods/demo/more-detail-tabs/controller.js
> +    @computed('selectedTab')
Why the extra space?

2018-05-30 14:30 UTC, notmessenger commented on tests/dummy/app/pods/demo/more-detail-tabs/controller.js
> +    @computed('subtabs', 'selectedTab')
Why the extra space?

2018-05-30 14:30 UTC, notmessenger commented
Need to merge in latest `master` branch

2018-05-30 14:32 UTC, notmessenger commented
Unrelated to your changes but if you remove the

`const Reporter = require('ember-test-utils/reporter')`

and 

`reporter: new Reporter(),`

lines from the _testem.js_ file it will resolve your CI build issues.

2018-05-30 14:50 UTC, notmessenger requested changes
If I visit http://ciena-frost.github.io/ember-frost-tabs/#/more-detail-tabs?selectedTab=AIS%20profile there are action icons displayed but when standing up your changes from this PR there are none and the console error of `Error: Assertion Failed: A component or helper named "frost-popover" could not be found`

2018-05-30 17:13 UTC, notmessenger requested changes
You have a conflict in your _package-lock.json_ file, likely due to not having merged in latest `master` first.

2018-05-30 17:13 UTC, notmessenger commented on package.json
> +    "ember-frost-popover": "^11.0.0",
Shouldn't this be a _dependency_ and not a _devDependency_ since it is required by consumers for this codebase to function correctly?

2018-05-30 17:14 UTC, notmessenger commented on package.json
> +    "ember-frost-popover": "^11.0.0",
Which then means this needs to be a MAJOR release and not a PATCH

2018-05-30 17:33 UTC, goforsatish commented
<img width="1679" alt="more-tabs" src="https://user-images.githubusercontent.com/33549703/40737172-a1632764-645d-11e8-8f2d-526e59d9793e.png">

2018-05-30 18:02 UTC, notmessenger requested changes
You are missing updates to the _package-lock.json_ file

2018-05-30 18:11 UTC, notmessenger commented
I have posted a screen recording of this new behavior and have posted it to https://youtu.be/JO5ijeNcqak

@ccampbel Is the "becoming larger and smaller again" effect on hover desired?  I'm fine with whatever is desired but I think you've only been looking at screenshots and not interactive behavior.

That also seems like a large bottom margin for triggering the popover but that is just my opinion.  Do we need to add another icon to the demo to get a better sense?

2018-05-30 18:13 UTC, notmessenger commented
@ccampbel @goforsatish the icon has a border on it as being clicked (browser effect) but remains once have finished clicking.  Is this desired?

<img width="79" alt="screen shot 2018-05-30 at 1 12 10 pm" src="https://user-images.githubusercontent.com/435544/40739221-2f23ab76-640b-11e8-986e-b056dcbdb0ab.png">

2018-05-30 18:21 UTC, notmessenger requested changes
How did you generate the update to the _package-lock.json_ file?  The changes within it do not reflect the changes made to the _package.json_ file.

2018-05-30 18:24 UTC, goforsatish commented
I generated package-lock.json by running npm install and merged it with the latest code from branch .

2018-05-30 18:30 UTC, notmessenger commented
Via `ember install ember-frost-popover`?

2018-05-30 18:31 UTC, goforsatish commented
No. I just did npm install.

2018-05-30 18:40 UTC, goforsatish commented
"ember-frost-popover" changes are there in package-lock.json. Is there still anything missing ?

2018-05-30 18:41 UTC, notmessenger commented
Okay, I see it now.  Maybe I was just looking at an outdated version.

2018-05-31 07:48 UTC, goforsatish commented
The the icon  border has been removed and it doesn't retain now on click of icon.

2018-05-31 13:00 UTC, notmessenger commented
@goforsatish if you run the command `npm set progress=false && rm -rf node_modules && rm -rf bower_components && npm install && bower cache clean &&  bower install` and then attempt to run either `ember s` or `ember test` do they run as expected or do you receive an error of

> Error: Cannot find module 'insert-module-globals'

2018-05-31 13:14 UTC, ccampbel commented
Hi @notmessenger - thanks for mentioning these details.  I have asked _Phil Savignac_ to take a look at these issues. 

RE: bigger & larger sizing on the icon as hover effect.  Generally speaking, the hover effect used across the frost components is not to resize, but to show a light blue background colour.  I think we should follow suit with that approach.

RE: large bottom margin for triggering the popover.  Yes, it does look rather large. This will mainly become an issue if/when another button is added below it.  I expect each button should have a same-sized target area for hover & click actions.

RE: leaving artifact in place around after click.  This is not the intent.  Making it look "pressed" only makes sense in the case where the overall UI has gone into some kind of "mode" that you need to represent to the user.  And they might need to press again to leave that mode.  In this case, I believe it will always cause another action to occur (e.g. dialog to open) that leaves no ambiguity for the user as to what they need to do next.

2018-06-01 05:05 UTC, goforsatish commented
@notmessenger 
Yes, I got  **Error: Cannot find module 'insert-module-globals'**  on ember s after executing the below commands:
 npm set progress=false && rm -rf node_modules && rm -rf bower_components && npm install && bower cache clean && bower install

2018-06-01 12:00 UTC, notmessenger commented
@goforsatish Then you need to fix this.  The most likely culprit is that your _package-lock.json_ file got messed up.

2018-06-11 17:06 UTC, goforsatish commented
<img width="716" alt="action-bar" src="https://user-images.githubusercontent.com/33549703/41246182-e245a7fc-6dc7-11e8-97fa-ce6049d9545d.png">

2018-06-11 17:14 UTC, Philsavignac commented
UX approved

2018-06-11 19:05 UTC, notmessenger approved these changes

2018-06-11 19:06 UTC, merged